### ISSUE TITLE
Screenshot and text differ on the lightning address landing page

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/website#17]
<meta name="lightning" content="you@lightning.address"/> does not yet fit to the screenshot.

What could be a minimal viable standard for this meta tag?

**Comment by bumi** [comment]
@MoritzKa what does this mean? 
Even though it might be duplicate for you and clear for you what differs best add what it should be in the issue.
also for example if we talk about "does not yet fit to the screenshot" in the issue we should remind ourselfs to mention which screenshot (link) we talk about.

**Comment by MoritzKa** [comment]
It is a question and a reminder of an open issue. But I should be more precise, yes. It is about the screenshot of the HTML code, that does not fit to the listed steps next to it. (Section: Own Website). 
I cannot say what has to be changed as we haven't come to decision here, have we?

**Comment by bumi** [comment]
ah I see. ok. thanks.

**Comment by MoritzKa** [comment]
![image](https://user-images.githubusercontent.com/13707997/152678474-235ca0d1-2275-4bd1-83c9-882ab637bf2b.png)
Could we align the description and the screenshot?

**Comment by bumi** [comment]
I've updated the text that it matches the screenshot.
both options currently work. 

the initial idea was to follow some existing spec like the [openalias](https://openalias.org/) spec to do that and to also be able to provide more details like for example a name or a description.
Or also support bolt12 in the future or just bolt11 invoices.

that would then be  bolt12:... instead of lnulrp:

**Comment by secondl1ght** [comment]
Closing this because it looks like @bumi resolved the issue.
