### ISSUE TITLE
Show link to login area

### ISSUE THREAD

**Issue by bumi** [getAlby/website#63]

**Comment by secondl1ght** [comment]
Do you know where you would like the link to be on the page?

**Comment by bumi** [comment]
nope. ideas?

**Comment by secondl1ght** [comment]
Ill do something up and post it here.

**Comment by secondl1ght** [comment]
I added a Login and Learn More (value4value) button to the navbar, I also removed the Add to Chrome button because it started to look crowded and don't know that we need it on the page twice. I put this in a new branch called 'add-links'. Here are screenshots, let me know what you think. Also we will need to change the Login button to Logout if a user is already logged in, do you know what variable I can use as a conditional statement for this?

![image](https://user-images.githubusercontent.com/85003930/152823205-0379e6a4-1523-43f2-a116-961fb5f5fea5.png)

**Comment by secondl1ght** [comment]
Mobile view:

![image](https://user-images.githubusercontent.com/85003930/152823366-e5657272-229f-4ac6-a013-f9cd5b1d2e88.png)

**Comment by secondl1ght** [comment]
I changed the button order because I think it makes more sense to have the Login on the right:
![image](https://user-images.githubusercontent.com/85003930/152933244-babbce42-ac5f-413d-8e27-b155977871af.png)

**Comment by secondl1ght** [comment]
I'll put in a PR for this so we can discuss more.

**Comment by bumi** [comment]
thanks @secondl1ght to tackle this...
@Tiana01 what do you think about this? how do we best setup such navigation?

**Comment by bumi** [comment]
thanks for sharing. good point about the social media links.
the value4value link is the tipping website you made (currently that's deployed under https://getalby.com/value4value )

so until we have those navigation links (features, about, etc.) filled we should make the tipping page a top level navigation entry?

**Comment by secondl1ght** [comment]
I agree we can remove the duplicate social links. We need a button somewhere to lead to the value4value page, otherwise nobody will know it exists so we added it for no reason. I just called it 'Learn more' but we can rename it whatever everyone likes. 

I will make the updates to the 'Login' and 'Install Alby' buttons and also remove the social links in my PR #67. Also @bumi do you know what `variable` I can use to check if a user is  logged in or not? 

Because I am assuming we will want to change the 'Login' button to say 'Logout' if they are already logged in right? Or what did you have in mind for that? Will they not come back to this page until they are logged out anyway?

**Comment by secondl1ght** [comment]
Ok I made some changes, here's how it looks currently:

![image](https://user-images.githubusercontent.com/85003930/153518400-46567426-ea0f-49ae-97a3-1b4e68b13d0f.png)

Let me know what you guys think!

**Comment by Tiana01** [comment]
We can have this. I don't think it is ideal to have 3 buttons in the navigation. There has to be some visual hierarchy, hence we can have the other one as a text as I've shown below

@bumi @secondl1ght also is "value4value" a phrase something that is commonly known and that you expect the users of this platform to understand without confusion? if it is then it's fine, if not, I believe we call it as it is... "tipping page or tipping landing page" to allow clarity.

<img width="764" alt="Screenshot 2022-02-11 at 09 50 36" src="https://user-images.githubusercontent.com/40744535/153562223-53c1577e-63f5-4ad8-9769-a3caea86a45a.png">

when we have more items in the navigation, it can look like this, since tipping is a feature of alby?
<img width="671" alt="Screenshot 2022-02-11 at 09 50 26" src="https://user-images.githubusercontent.com/40744535/153562882-fe470ac4-92bd-49cf-a1ce-9e8c6a3be3b8.png">

**Comment by Tiana01** [comment]
@secondl1ght you could also refer to the Figma file with the designs worked on to ensure that the design implementation matches the design in style, font size etc

**Comment by bumi** [comment]
Value4Value is a known term or a term that is getting more popular. it typically comes from the podcasting world, but also with Alby it will spread to more digital content worlds: http://value4value.io/

//cc tagging @MoritzKa that he can follow and comment

**Comment by secondl1ght** [comment]
How's this? I can merge these changes if everyone likes them:

**Comment by secondl1ght** [comment]
Ok I have merged the PR making this the new look for the top navbar, so I will close this issue now. Any feedback once it is live please create a new issue.
